---
- name: restart php
  service:
    name: "php{{ item }}-fpm"
    state: restarted
  loop: "{{ changed_php_versions }}"
  when: changed_php_versions | length > 0
  loop_control:
    label: "{{ item }}"
